/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "../../lib/types";
// tslint:disable:object-literal-key-quotes

export const ShapeKind = t.enumtype({
  "Square": 0,
  "Rectangle": 1,
  "Circle": 2,
});

export const Shape = t.iface([], {
  "kind": "ShapeKind",
});

export const Square = t.iface(["Shape"], {
  "kind": t.enumlit("ShapeKind", "Square"),
  "size": "number",
});

export const Rectangle = t.iface(["Shape"], {
  "kind": t.enumlit("ShapeKind", "Rectangle"),
  "width": "number",
  "height": "number",
});

export const Circle = t.iface(["Shape"], {
  "kind": t.enumlit("ShapeKind", "Circle"),
  "radius": "number",
});

const exportedTypeSuite: t.ITypeSuite = {
  ShapeKind,
  Shape,
  Square,
  Rectangle,
  Circle,
};
export default exportedTypeSuite;
