/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "../../lib/types";
// tslint:disable:object-literal-key-quotes

export const FormConfig = t.iface([], {
  "children": t.opt(t.array("FormConfig")),
});

const exportedTypeSuite: t.ITypeSuite = {
  FormConfig,
};
export default exportedTypeSuite;
